default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  encoding: utf8mb4
  database: pass_development
  username: myappuser
  password: myapppassword
  host: db

test:
  <<: *default
  encoding: utf8
  database: pass_development
  username: myappuser
  password: myapppassword
  host: db


production:
  <<: *default
  database: storage/production.sqlite3
